# Generated by Django 2.2.2 on 2019-06-14 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPCheckResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('query_result', models.DecimalField(decimal_places=5, max_digits=8)),
                ('is_authorized', models.BooleanField(default=False)),
                ('entry_time', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='RateLimitState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_count', models.IntegerField()),
                ('last_reset_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WhitelistEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('ip_address', models.GenericIPAddressField()),
                ('subnet', models.IntegerField(default=32)),
            ],
        ),
    ]
